const games = {
    tetris: {
        title: "Twitch Tetris",
        url: "game-template.html?id=tetris",
        originalUrl: "https://emulatoros.github.io/gfile/tetris/index.html",
        image: "images/proxyandgameimages/gameimages/tetris.png",
        description: "You know what this is, a ripoff of Tetris.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    cookieClicker: {
        title: "Cookie Clicker (first method)",
        url: "game-template.html?id=cookieClicker",
        originalUrl: "https://ozh.github.io/cookieclicker/",
        image: "images/proxyandgameimages/gameimages/cookie.jpeg",
        description: "Won't be blocked if it's on GitHub! (this one click link to the game)",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    cookieClickerLocal: {
        title: "Cookie Clicker (second method)",
        url: "game-template.html?id=cookieClickerLocal",
        originalUrl: "Games/html5-games/cookieclicker/index.html",
        image: "images/proxyandgameimages/gameimages/cookie.jpeg",
        description: "Won't be blocked if it's on GitHub! (this one click link to the game)",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex8: {
        title: "Vex 8",
        url: "game-template.html?id=vex8",
        originalUrl: "https://ubg98.github.io/Vex8/",
        image: "images/proxyandgameimages/gameimages/vex8.jpeg",
        description: "Eighth Game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex7: {
        title: "Vex 7",
        url: "game-template.html?id=vex7",
        originalUrl: "https://ubg98.github.io/Vex7/",
        image: "images/proxyandgameimages/gameimages/vex7.jpeg",
        description: "The seventh game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex6: {
        title: "Vex 6",
        url: "game-template.html?id=vex6",
        originalUrl: "https://ubg98.github.io/Vex6/",
        image: "images/proxyandgameimages/gameimages/vex6.jpeg",
        description: "The sixth game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex5: {
        title: "Vex 5",
        url: "game-template.html?id=vex5",
        originalUrl: "https://vex5online.github.io/file/",
        image: "images/proxyandgameimages/gameimages/vex5.jpeg",
        description: "The fifth game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex4: {
        title: "Vex 4",
        url: "game-template.html?id=vex4",
        originalUrl: "https://ubg98.github.io/Vex4/",
        image: "images/proxyandgameimages/gameimages/vex4.jpeg",
        description: "The fourth game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex3: {
        title: "Vex 3",
        url: "game-template.html?id=vex3",
        originalUrl: "https://ubg98.github.io/Vex3/",
        image: "images/proxyandgameimages/gameimages/vex3.jpeg",
        description: "The third game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex2:{
        title: "Vex 2",
        url: "game-template.html?id=vex2",
        image: "images/proxyandgameimages/gameimages/vex2.jpeg",
        originalUrl: "Games/html5-games/vex2/vex2.html",
        description: "The second vex",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    vex:{
        title: "Vex",
        url: "game-template.html?id=vex",
        image: "images/proxyandgameimages/gameimages/vex.png",
        originalUrl: "Games/html5-games/vex/index.html",
        description: "The orginal vex, in one piece.",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    bigTower1: {
        title: "Big Tower Tiny Square 1",
        url: "game-template.html?id=bigTower1",
        originalUrl: "https://ubg98.github.io/BigTowerTinySquare/",
        image: "images/proxyandgameimages/gameimages/bigsquare1.jpeg",
        description: "Goofy Platformer.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    bigTower2: {
        title: "Big Tower Tiny Square 2",
        url: "game-template.html?id=bigTower2",
        originalUrl: "https://rebemanae.github.io/big-tower-tiny-square-2/",
        image: "images/proxyandgameimages/gameimages/bigsquare2.jpeg",
        description: "Even more Goofy Platformer.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    ovo: {
        title: "0v0",
        url: "game-template.html?id=ovo",
        originalUrl: "https://23azostore.github.io/s/ovo/",
        image: "images/proxyandgameimages/gameimages/0v0.png",
        description: "Such a Classic!",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    evolve: {
        title: "Evolve",
        url: "game-template.html?id=evolve",
        originalUrl: "https://pmotschmann.github.io/Evolve/",
        image: "images/proxyandgameimages/gameimages/Evolve.png",
        description: "An idle game where you Evolve your own species",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    intoSpace2: {
        title: "Into Space 2",
        url: "game-template.html?id=intoSpace2",
        originalUrl: "https://images-opensocial.googleusercontent.com/gadgets/ifr?url=https://s3.amazonaws.com/production-assetsbucket-8ljvyr1xczmb/1ee20621-61bc-4ec8-a8ec-5e839c2e6edc%2Finto-space-2.xml&container=ig",
        image: "images/proxyandgameimages/gameimages/intospace2.png",
        description: "Build and launch your rocket into space!",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    paperclips: {
        title: "Universal Paperclips",
        url: "game-template.html?id=paperclips",
        originalUrl: "https://memalign.github.io/m/universal-paperclips/index2.html",
        image: "images/proxyandgameimages/gameimages/paperclip.jpeg",
        description: "Paperclips... Amazing",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    idlegamedev: {
        title: "Idle Idle Game Dev",
        url: "game-template.html?id=idlegamedev",
        originalUrl: "https://luts91.github.io/idle-idle-gamedev/index.html",
        image: "images/proxyandgameimages/gameimages/idlegamedev.jpeg",
        description: "A idle game revolved around making idle games. Weird.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    idledice: {
        title: "Idle Dice",
        url: "game-template.html?id=idledice",
        originalUrl: "https://luts91.github.io/idle-dices/index.html",
        image: "images/proxyandgameimages/gameimages/idledice.jpeg",
        description: "A idle game revolved around gambli- I mean rolling dice!",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    spiceIdle: {
        title: "Spice Idle",
        url: "game-template.html?id=spiceIdle",
        originalUrl: "https://zakuro98.github.io/Spice-Idle/",
        image: "images/proxyandgameimages/gameimages/spiceidle.jpeg",
        description: "Mhm. Powder.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    dash: {
        title: "Geometry Dash",
        url: "game-template.html?id=dash",
        originalUrl: "https://edug309.github.io/g8/geometry-dash/",
        image: "images/proxyandgameimages/gameimages/geometry-dash.png",
        description: "Scratch Rippoff",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    bottleFlip: {
        title: "Bottle Flip",
        url: "game-template.html?id=bottleFlip",
        originalUrl: "https://edug309.github.io/g69/bottle-flip/",
        image: "images/proxyandgameimages/gameimages/bottle-flip.png",
        description: "2017",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    connect4: {
        title: "Connect 4",
        url: "game-template.html?id=connect4",
        originalUrl: "https://www.calculators.org/games/connect-4/game.php",
        image: "images/proxyandgameimages/gameimages/connect4.jpeg",
        description: "Connect 4. Pretty simple.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    expsim: {
        title: "EXP Simulator",
        url: "game-template.html?id=expsim",
        originalUrl: "https://zakuro98.github.io/EXP-Simulator/",
        image: "images/proxyandgameimages/gameimages/paperclip.jpeg",
        description: "... Amazing",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    bitlife: {
        title: "Bitlife",
        url:"game-template.html?id=bitlife",
        originalUrl: "https://bitlifeonline.github.io/class/index.html",
        image: "images/proxyandgameimages/gameimages/bitlife.png",
        description: "Not realistic life simulator. 2019 version o/bitlife",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    slope: {
        title: "Slope",
        url: "game-template.html?id=slope",
        originalUrl: "Games/html5-games/slope/index.html",
        image: "images/proxyandgameimages/gameimages/slope.png",
        description: "A platform game based off slope. Or is it?",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    raftWars1:{
        title: "Raft Wars 1",
        url: "game-template.html?id=raftWars1",
        originalUrl: "https://abinbins.github.io/a/raft-wars/",
        image: "images/proxyandgameimages/gameimages/raftWars1.png",
        description: "Hmm.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    raftWars2: {
        title: "Raft Wars 2",
        url: "game-template.html?id=raftWars2",
        originalUrl: "https://tag-2.github.io/a6/raft-wars-2/",
        image: "images/proxyandgameimages/gameimages/raftWars2.png",
        description: "Hmm.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    poolBall: {
        title: "Pool",
        url: "game-template.html?id=poolBall",
        image: "images/proxyandgameimages/gameimages/poolball.jpeg",
        originalUrl: "https://edug309.github.io/g8/8-ball-pool/",
        description: "Ripoff CoolMathGames Pool",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    redBall4: {
        title: "Red Ball 4",
        url: "game-template.html?id=redBall4",
        image: "images/proxyandgameimages/gameimages/redball4.webp",
        originalUrl: "https://edug309.github.io/g177/red-ball-4/",
        description:"A red ball thats trying to find its way.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    superMario: {
        title: "Super Mario",
        url: "game-template.html?id=superMario",
        image: "images/proxyandgameimages/gameimages/super-mario-bros.png",
        originalUrl: "https://edug309.github.io/g9/super-mario-bros/",
        description:"You know this game.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    slope2: {
        title: "Slope 2",
        url: "game-template.html?id=slope2",
        image: "images/proxyandgameimages/gameimages/slope2.jpeg",
        originalUrl: "https://edug309.github.io/g6/slope-2/",
        description:"Slope Sequal!",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    papasCheese: {
        title: "Papas Cheeseria",
        url: "game-template.html?id=papasCheese",
        image: "images/proxyandgameimages/gameimages/papas-cheeseria.png",
        originalUrl: "https://edug309.github.io/g50/papas-cheeseria/",
        description:"One of the papas pizzaria games.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    dodgeMiner:{
        title: "Dodge Miner",
        url: "game-template.html?id=dodgeMiner",
        image: "images/proxyandgameimages/gameimages/dodgeMiner.jpeg",
        originalUrl: "https://yalogames.github.io/DogeMiner/",
        description: "One of the OG idle games...",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    dodgeMiner2:{
        title: "Dodge Miner 2",
        url: "game-template.html?id=dodgeMiner2",
        image: "images/proxyandgameimages/gameimages/dodgeMiner2.jpeg",
        originalUrl: "https://gnhustgames.github.io/dgmn2/",
        description: "The Sequal",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    papasPizzaria:{
        title: "Papas Pizzaria",
        url: "game-template.html?id=papasPizzaria",
        image: "images/proxyandgameimages/gameimages/papasPizza.jpeg",
        originalUrl: "https://yalogames.github.io/papaspizzaria/",
        description: "Papa's Pizzaria Franchise",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    papasBurger:{
        title: "Papas Burgeria",
        url: "game-template.html?id=papasBurger",
        image: "images/proxyandgameimages/gameimages/papasBurger.jpeg",
        originalUrl: "https://yalogames.github.io/papasburgeria/",
        description: "Papa's Pizzaria Franchise",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    paperIo:{
        title: "Paper.io",
        url: "game-template.html?id=paperIo",
        image: "images/proxyandgameimages/gameimages/paperIo.jpeg",
        originalUrl: "https://yalogames.github.io/paperio2/",
        description: "The second paper.io",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    click: {
        title:"Click. (my game)",
        url: "game-template.html?id=click",
        image: "images/proxyandgameimages/gameimages/paperclip.jpeg",
        originalUrl: "https://bcrhbrhcdb.github.io/click/",
        description: "my gaem :)",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    crossyRoads: {
        title:"Crossy Roads",
        url: "game-template.html?id=crossyRoads",
        image: "images/proxyandgameimages/gameimages/crossyRoads.jpeg",
        originalUrl: "https://lnahtml.github.io/a/crossy-road/",
        description: "A game where a chicken tries to survive crossing a highway..",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    picross: {
        title: "Picross",
        url: "game-template.html?id=picross",
        image: "images/proxyandgameimages/gameimages/picross.jpeg",
        originalUrl: "https://liouh.com/picross/",
        description: "Math.",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    slope3: {
        title: "Slope 3",
        url: "game-template.html?id=slope3",
        image: "images/proxyandgameimages/gameimages/slope3.jpeg",
        originalUrl: "https://ubg44.github.io/Slope3/",
        description: "Third Game",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    snake: {
        title: "Snake",
        url: "game-template.html?id=snake",
        image: "images/proxyandgameimages/gameimages/snake.jpeg",
        originalUrl: "Games/html5-games/snake/index.html",
        description: "Snake Rippoff",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    2048: {
        title: "2048 (HTML5)",
        url: "game-template.html?id=2048",
        image: "images/proxyandgameimages/gameimages/2048.png",
        originalUrl: "Games/html5-games/2048/index.html",
        description: "Merge two of the same number until you get to 2048. Easy.",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    ticTacToe: {
        title: "Tic-Tac-Toe",
        url: "game-template.html?id=ticTacToe",
        image: "images/proxyandgameimages/gameimages/tic-tac-toe.png",
        originalUrl: "Games/html5-games/tic-tac-toe/index.html",
        description: "Classic game of Tic Tac Toe",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    hangman: {
        title: "Hangman",
        url: "game-template.html?id=hangman",
        image: "images/proxyandgameimages/gameimages/hang-man.jpeg",
        originalUrl: "Games/html5-games/hang-man/index.html",
        description: "Hangman is a guessing game for two or more players.",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    flappyBird: {
        title: "Flappy Bird",
        url: "game-template.html?id=flappyBird",
        image: "images/proxyandgameimages/gameimages/flappy-bird.jpeg",
        originalUrl: "Games/html5-games/flappy-bird/index.html",
        description: "Back to 2016",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    pingPong: {
        title: "Ping Pong",
        url: "game-template.html?id=pingPong",
        image: "images/proxyandgameimages/gameimages/ping-pong.png",
        originalUrl: "Games/html5-games/ping-pong/index.html",
        description: "A game where you pass a cube to each other.",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    minesweeper: {
        title: "Minesweeper",
        url: "game-template.html?id=minesweeper",
        image: "images/proxyandgameimages/gameimages/minesweeper.png",
        originalUrl: "Games/html5-games/minesweeper/index.html",
        description: "Guess where mines are, but don't make the wrong choice.",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
    papasScooperia:{
        title: "Papas Scooperia",
        url: "game-template.html?id=papasScooperia",
        image: "images/proxyandgameimages/gameimages/papasScoop.jpeg",
        originalUrl: "Games/html5-games/papas-scoop/index.html",
        description: "Another papas pizzaeria game...",
        type: "folder",
        ratings: [],
        likes: 0,
        dislikes: 0,
    },
}
